name: cbt_mobile_application
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  awesome_snackbar_content: ^0.1.3
  cached_network_image: ^3.2.3
  camera: ^0.10.5+2
  cloud_firestore: ^4.8.1
  cupertino_icons: ^1.0.5
  easy_separator: ^1.0.1
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_storage:
  flutter:
    sdk: flutter
  get: ^4.6.5
  google_fonts:
  google_mlkit_face_detection: ^0.8.0
  google_sign_in: ^6.1.4
  image: ^4.0.17
  liquid_swipe: ^3.1.0
  path_provider: ^2.0.15
  percent_indicator: ^4.2.3
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/DB/papers/
    - assets/images/splash_images/
