name: cbt_mobile_application
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  cloud_firestore: ^4.8.1
  firebase_core: ^2.14.0
  flutter:
    sdk: flutter
  get: ^4.6.5
  google_fonts: ^5.1.0
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/DB/papers/
    - assets/images/splash_images/
