// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1ulq4wXsgTUNN0ZLsXZsm07wjWeV13m4',
    appId: '1:90915404796:web:3e15f0a7b8e43d238d5079',
    messagingSenderId: '90915404796',
    projectId: 'cbt-mobile-application',
    authDomain: 'cbt-mobile-application.firebaseapp.com',
    storageBucket: 'cbt-mobile-application.appspot.com',
    measurementId: 'G-P9L0QC69VF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwP5KrGi842NsaPWFgugYe4xnIBejHGIU',
    appId: '1:90915404796:android:8101c18094344de38d5079',
    messagingSenderId: '90915404796',
    projectId: 'cbt-mobile-application',
    storageBucket: 'cbt-mobile-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs9u31MJc-AIjNgdZ9Yyi6NAA82_TiPxk',
    appId: '1:90915404796:ios:4e54a821097982cd8d5079',
    messagingSenderId: '90915404796',
    projectId: 'cbt-mobile-application',
    storageBucket: 'cbt-mobile-application.appspot.com',
    iosClientId: '90915404796-70aiv8qhn3c6ptkurvabp1aak3hs551r.apps.googleusercontent.com',
    iosBundleId: 'com.example.cbtMobileApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs9u31MJc-AIjNgdZ9Yyi6NAA82_TiPxk',
    appId: '1:90915404796:ios:1ebe3ed7f3235dd28d5079',
    messagingSenderId: '90915404796',
    projectId: 'cbt-mobile-application',
    storageBucket: 'cbt-mobile-application.appspot.com',
    iosClientId: '90915404796-12idg1dteu9trj34o4lio688mg24i5n5.apps.googleusercontent.com',
    iosBundleId: 'com.example.cbtMobileApplication.RunnerTests',
  );
}
